language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install zc.buildout
  - git clone git://github.com/TangledWeb/tangled ../tangled
  - buildout
script:
  - ./bin/tangled test
  - ./bin/sphinx-build -E docs docs/_build
